dataset_path: data/raw/Gas_Sensors_Measurements.csv
dataset_processed_path: data/processed/Gas_Sensors_Measurements.csv
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_feng_set_path:
- data/processed/x_train_feng.pkl
- data/processed/y_train_feng.pkl
valid_feng_set_path:
- data/processed/x_valid_feng.pkl
- data/processed/y_valid_feng.pkl
test_feng_set_path:
- data/processed/x_test_feng.pkl
- data/processed/y_test_feng.pkl

production_model_path: models/production_model.pkl
training_log_path: log/training_log.json

# Debug related
print_debug: true

# Predictors and label related
label: Gas
predictors:
- MQ2
- MQ3
- MQ5
- MQ6
- MQ7
- MQ8
- MQ135

# Column by data type
int_columns:
- MQ2
- MQ3
- MQ5
- MQ6
- MQ7
- MQ8
- MQ135
obj_columns:
- Gas

# Target classes
target_classes:
- NoGas
- Perfume
- Smoke
- Mixture

range_sensor_val:
- 0
- 1000