dataset_path: data/raw/Gas_Sensors_Measurements.csv
dataset_processed_path: data/processed/Gas_Sensors_Measurements.csv
encoder_classes:
- Mixture
- NoGas
- Perfume
- Smoke
int_columns:
- MQ2
- MQ3
- MQ5
- MQ6
- MQ7
- MQ8
- MQ135
label: Gas
obj_columns:
- Gas
ohe_gas_path: models/ohe_station.pkl
predictors:
- MQ2
- MQ3
- MQ5
- MQ6
- MQ7
- MQ8
- MQ135
print_debug: true
production_model_path: models/production_model.pkl
range_sensor_val:
- 0
- 1000
target_classes:
- NoGas
- Perfume
- Smoke
- Mixture
test_feng_set_path:
- data/processed/x_test_feng.pkl
- data/processed/y_test_feng.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_feng_set_path:
- data/processed/x_train_feng.pkl
- data/processed/y_train_feng.pkl
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
training_log_path: log/training_log.json
valid_feng_set_path:
- data/processed/x_valid_feng.pkl
- data/processed/y_valid_feng.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
